#!/usr/bin/env python3
"""
Main entry points. Loads the configuration, then the UI
"""

from libnctelegram.config import load_config
from libnctelegram.telegram_ui import Telegram_ui


# Load configuration
config_full = load_config()

# Run main UI
Telegram_ui(config_full)
